### ISSUE TITLE
pdfrx may be slow in some cases

### ISSUE THREAD

**Issue by qmr777** [espresso3389/pdfrx#168]
I found that in some cases, pdfrx's speed of loading page images would be slower.

For example:

1. Trying to open a large PDF file, let's call it PDF A.
2. Opening a regular PDF file, let's call it PDF B.
3. Attempting to render a page from PDF B.

In this scenario, rendering the page from PDF B is slower than usual, especially after having tried to open the larger PDF A. Only after PDF A has finished loading, PDF B will start to load.

I found that pdfrx uses a `BackgroundWorker`  internally to handle all tasks, which is essentially a single-threaded worker that handle asynchronous behavior.

Can we change this situation, for example, using a separate `BackgroundWorker` for each `PDFDocument`?

**Comment by espresso3389** [comment]
[1.0.58](https://github.com/espresso3389/pdfrx/blob/master/CHANGELOG.md#1058) fixes concurrency issues caused by misunderstanding of pdfium threading model.

And the fix synchronizes all the pdfium API calls even if they are not for the same PDF document.

In your case, PDF A loading process blocks loading of PDF B loading. The loading of the documents does not run concurrently.

It's a pdfium limitation. Not a pdfrx limitation.
We should consider some kind of out of process PDF loading model but it's too complex and not easily realized.
