### ISSUE TITLE
EXAMPLE: markers are not reset on document reload

### ISSUE THREAD

**Issue by dineshnaikb** [espresso3389/pdfrx#189]
onDocumentChanged the mark store and not able remove

![Screenshot 2024-06-22 102916](https://github.com/espresso3389/pdfrx/assets/32676675/fe7b28b6-fd50-4de7-81a4-ece912d91cf4)

this may take half of the page load 1 and half 2. then i have marked in page 2 it effects on page 1 and not removable 

@espresso3389

**Comment by espresso3389** [comment]
Please note that the example is just an example. I'll update it but it's very low priority...

And, your title does not explain anything about the issue.

**Comment by dineshnaikb** [comment]
# problem statement
marking the selected text not working fine, not only in example, everywhere.
## user interaction
* opened PDF and scroll little to visible of second page but not full second  page then user marked 
![image](https://github.com/espresso3389/pdfrx/assets/32676675/a4d6e13c-bf0a-4053-a4b3-5763831d93da)
* show the selected text is **2nd page** but marked box in **1st page**
![image](https://github.com/espresso3389/pdfrx/assets/32676675/b582973e-f0fa-47e0-92f4-d6a23ac7650e)
as showed in image the box has not but also marked what i want to say is the how to get the page number of select text
```
void _addCurrentSelectionToMarkers(Color color) {
    if (controller.isReady && controller.pageNumber != null && _selectedText != null && _selectedText!.isNotEmpty) {
      _markers.putIfAbsent(controller.pageNumber!, () => []).add(Marker(color, _selectedText!));
      setState(() {});
    }
  }
```

 controller.pageNumber of selected text 


@espresso3389

**Comment by espresso3389** [comment]
I've found the root cause of the issue. PdfViewerController.goTo or such function now internally call PdfViewerController.setCurrentPageNumber and then even if you select some text on "another" page, the current page number is not correctly updated. So the marker created on the page does not have the correct page number.

**Comment by espresso3389** [comment]
There two things to take into consideration:
- For the consisntency on PdfViewer, current page number should be updated on such operation.
- For the example code, we must use `PdfTextRanges.pageNumber` rather than `PdfViewerController.pageNumber`

And the first one is not so easy to fix. It was introduced on 1.0.68 that fixes #152 (cb74d2f24502e4b357f7b4932859736717635be0) but we need to consider more about the internal consistency...

The second one is easy and already has a fix on 1b33413d326c35eca4ff89ede6e00b4b24903c6c.

**Comment by dineshnaikb** [comment]
![image](https://github.com/user-attachments/assets/46e63437-c089-4e1e-ab3f-26152876af06)
in some pdf, the marking is not placed correctly due to layout issues or any other reason.
but the size of the text was correct marking but the placement goes a little differently 
example as shown in the image where two words were correctly placed but see the bottom of the image it was wrongly placed
pls check this
@espresso3389

**Comment by espresso3389** [comment]
There seems some kind of mis-calculation of text index.

From the screenshot, I'm guessing that for the 3rd one, indexOf("where") on the "Countries where" returns 5 instead of 10. The 4th one return 3.

The calculation of the text index is accumlative. So some letters on the text mis-increase the text index and it results in such problem.

If possible, could you allow me to access the PDF file (Or at least the page of the problem) to reproduce the issue?

**Comment by dineshnaikb** [comment]
[Pulp_Paper_and_Packaging_Guidelines_June_21_1685614275 (2)_1698976928 (1)_1698977318_1698977700_1698982520 (1)_1699000343_1699005244.pdf](https://github.com/user-attachments/files/16359854/Pulp_Paper_and_Packaging_Guidelines_June_21_1685614275.2._1698976928.1._1698977318_1698977700_1698982520.1._1699000343_1699005244.pdf)
pdf sample
