### ISSUE TITLE
perPageSelectionAreaInjector isn't defined starting with version 1.0.85

### ISSUE THREAD

**Issue by tc4u** [espresso3389/pdfrx#256]
I was using version 1.0.84 and recently tried to upgrade to the latest 1.0.88 version, but I'm getting an error stating that perPageSelectionAreaInjector isn't defined. I'm using this to display a custom selection menu for my PDF and it was working well with text selection. Is there another way I can go about update triggering a custom context menu with the latest pdfrx version? Thank you.

**Comment by espresso3389** [comment]
`perPageSelectionAreaInjector` was removed at 9fe0f95fec0913188bc9eda99e26d084869ae52d.

And, the decision made on the commit is that, we finally gave up to support per-page `SelectionArea` because it caused several undesired effects. Currently, we have only one `SelectionArea` that contains `InteractiveViewer`.

Anyway, for what purpose are you using `perPageSelectionAreaInjector`? Currently, you can disable `SelectionArea` inside `PdfViewer` by setting `enableTextSelection=false`.

**Comment by tc4u** [comment]
Thank you for your reply. This is my pubspec: pdfrx: 1.0.84, so not sure. I was using this method to display a custom context menu for pdf text selection. Is there another way I can go about displaying a custom context menu after text is selected, rather than the default one? The only way I'm aware of was by using the perPageSelectionAreaInjector callback to provide my own context menu text and callbacks. Again, thank you for your great work on pdfrx.

**Comment by espresso3389** [comment]
OK, now we have `selectableRegionInjector`/`perPageSelectableRegionInjector` to inject `SelectableRegion` or `SelectionArea` (or anything such) to document-level and page-level.

`selectableRegionInjector` is almost same effect to `enableTextSelection=true` but you can customize `SelectableRegion`.
Another one, `perPageSelectableRegionInjector` is to inject some on each page.

```dart
PdfViewerParams(
  // you don't need enableTextSelection here
  perPageSelectableRegionInjector:
    (context, child, page, pageRect) => SelectionArea(child: child),
  ...
),
```

**Comment by tc4u** [comment]
Sorry for my delay in responding. Thank you so much for the clarification and the relevant methods. I'll take a look at your latest changes!
